#ifndef CGEN_VERSION_HPP
#define CGEN_VERSION_HPP

#include <string>

namespace cgen {

namespace version {

// app version
// todo: should be autogenerated from current git tag
inline constexpr int major = 1;
inline constexpr int minor = 1;
inline constexpr int patch = 1;

// resolved file format version
inline constexpr int resolved = 1;

// cmake version
inline constexpr char cmake[] = "3.11";

} // namespace version

auto version_string() -> std::string;

} // namespace cgen

#endif // ifndef CGEN_VERSION_HPP
