project: cgen

templates:
  common:
    properties:
      CXX_STANDARD: 20
      CXX_STANDARD_REQUIRED: ON
    compile_options:
      global:
        - -Wall
        - -Wextra
        - -Wpedantic
      configurations:
        Release:
          - -Werror

  asan:
    compile_options:
      configurations:
        Asan:
          - ${CMAKE_CXX_FLAGS_DEBUG}
          - -O1
          - -fno-omit-frame-pointer
          - -fno-optimize-sibling-calls
          - -fsanitize=address
    link_options:
      configurations:
        Asan:
          - ${CMAKE_EXE_LINKER_FLAGS_DEBUG}
          - -g
          - -fsanitize=address

  ubsan:
    compile_options:
      configurations:
        Ubsan:
          - ${CMAKE_CXX_FLAGS_DEBUG}
          - -O1
          - -fno-omit-frame-pointer
          - -fno-optimize-sibling-calls
          - -fsanitize=undefined
          - -fno-sanitize-recover
    link_options:
      configurations:
        Ubsan:
          - ${CMAKE_EXE_LINKER_FLAGS_DEBUG}
          - -g
          - -fsanitize=undefined

packages:
  - external: external/doctest
    if: PROJECT_IS_TOP_LEVEL
    url: https://github.com/doctest/doctest
    options:
      DOCTEST_NO_INSTALL: ON

  - external: external/yaml-cpp
    url: https://github.com/jbeder/yaml-cpp
    options:
      YAML_BUILD_SHARED_LIBS: OFF
      YAML_CPP_BUILD_CONTRIB: OFF
      YAML_CPP_BUILD_TOOLS: OFF
      YAML_CPP_FORMAT_SOURCE: OFF

  - external: external/miroir
    url: https://github.com/m6vrm/miroir

  - external: external/poost
    url: https://github.com/m6vrm/poost

targets:
  - library: libcgen_obj
    type: object
    templates:
      - common
    sources:
      - include/libcgen/codegen.hpp
      - include/libcgen/config.hpp
      - include/libcgen/error.hpp
      - include/libcgen/packages.hpp
      - include/libcgen/version.hpp
      - src/libcgen/cgen.schema.yml.in
      - src/libcgen/codegen.cpp
      - src/libcgen/config.cpp
      - src/libcgen/debug.cpp
      - src/libcgen/debug.hpp
      - src/libcgen/error.cpp
      - src/libcgen/exec.hpp
      - src/libcgen/fs.cpp
      - src/libcgen/fs.hpp
      - src/libcgen/git.cpp
      - src/libcgen/git.hpp
      - src/libcgen/packages.cpp
      - src/libcgen/preproc.cpp
      - src/libcgen/preproc.hpp
      - src/libcgen/version.cpp
      - src/libcgen/versions.cpp
      - src/libcgen/versions.hpp
    includes:
      public:
        - include
      private:
        - include/libcgen
        - src/libcgen
    dependencies:
      public:
        - yaml-cpp
      private:
        - miroir::miroir
        - poost::poost

  - library: libcgen
    templates:
      - common
    aliases:
      - cgen::libcgen
    sources:
      - src/libcgen/exec_impl.cpp
      - src/libcgen/fs_impl.cpp
    includes:
      - src/libcgen
    dependencies:
      public:
        - libcgen_obj
      private:
        - poost::poost

  - executable: libcgen_test
    if: PROJECT_IS_TOP_LEVEL
    templates:
      - common
      - asan
      - ubsan
    sources:
      - tests/codegen_test.cpp
      - tests/config_test.cpp
      - tests/exec_mock.cpp
      - tests/fs_mock.cpp
      - tests/fs_test.cpp
      - tests/main_test.cpp
      - tests/mocks.hpp
      - tests/packages_test.cpp
      - tests/preproc_test.cpp
      - tests/versions_test.cpp
    includes:
      - include/libcgen
      - src/libcgen
      - tests
    dependencies:
      - doctest::doctest
      - libcgen_obj
      - poost::poost

  - executable: cgen
    templates:
      - common
    sources:
      - src/cgen/main.cpp
    includes:
      - src/cgen
    dependencies:
      - cgen::libcgen
      - poost::poost
